CREATE USER sbard;
ALTER USER sbard WITH PASSWORD 'gange';
CREATE USER api;
ALTER USER api WITH PASSWORD '32&b5J!Z&aze';
CREATE DATABASE nohouse;
GRANT ALL PRIVILEGES ON DATABASE nohouse TO api;
GRANT ALL PRIVILEGES ON DATABASE nohouse TO sbard;
ALTER DEFAULT PRIVILEGES GRANT ALL ON TABLES TO api;
ALTER DEFAULT PRIVILEGES GRANT ALL ON TABLES TO sbard;